version: "3.8"
services:
  app:
    image: python:3.8-slim-buster
    command: bash -c "ls && pip install -r requirements.txt && python -m flask run --host=0.0.0.0"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5000:5000