version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8.8
    steps:
      - checkout
      - run: python --version
      - run: pip install -r requirements.txt
      - run:
          name: Running Server
          command: python app.py
          background: true
      - run: python -m unittest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
