version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8.8
    steps:
      - checkout
      - run: python --version
      - run: pip install -r requirements.txt
      - run: docker build -t bookshop .
      - run:
          name: Running Server
          command: docker run --publish 5000:5000 bookshop
          background: true
      - run: python -m unittest discover tests/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
