version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: python --version
      - setup_remote_docker:
           version: 20.10.6
      - run: pip install -r requirements.txt
      - run: python -m unittest discover tests/
      - run: docker build -t bookshop .
      - run: echo $CURRENT_ENVIRONMENT

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
